cassandra.host=localhost
cassandra.port=9042
cassandra.keyspace=railmarkov
cassandra.replication={'class': 'SimpleStrategy', 'replication_factor': 1}
cassandra.table=events
datagen.railcars=100
datagen.events_per_railcar=100