CASSANDRA_HOST=localhost
CASSANDRA_PORT=9042
CASSANDRA_KEYSPACE=railmarkov
CASSANDRA_KEYSPACE_REPLICATION="{'class': 'SimpleStrategy', 'replication_factor': 1}"
CASSANDRA_TABLE=events
DATAGEN_RAILCARS=0
DATAGEN_EVENTS_PER_RAILCAR=100
MARKOV_TRANSITION_MATRIX_FILE=src/main/resources/transition_matrix.txt