A:
  TY: 0.95
  UI: 0.03
  BO: 0.02

R: null

TY:
  AY: 0.97
  SW: 0.01
  BO: 0.02

SW:
  AY: 0.97
  BO: 0.02
  TYS: 0.01

AY:
  UI: 0.35
  TI: 0.25
  TY: 0.20
  TYS: 0.08
  SW: 0.11
  BO: 0.01

TYS:
  IYS: 0.95
  AY: 0.03
  BO: 0.02

IYS:
  FYS: 0.99
  BO: 0.01

FYS:
  AY: 0.75
  SW: 0.24
  BO: 0.01

UI:
  TI: 0.47
  TY: 0.47
  AY: 0.04
  BO: 0.02

BO:
  UR: 0.96
  R: 0.02
  TYS: 0.02

UR:
  SW: 0.58
  TYS: 0.20
  AY: 0.18
  BO: 0.04

TI:
  AI: 0.99
  BO: 0.01

AI:
  TIS: 0.90
  TY: 0.05
  TI: 0.03
  BO: 0.02

TIS:
  AIS: 0.90
  FIS: 0.09
  BO: 0.01

AIS:
  L: 0.47
  U: 0.47
  FIS: 0.04
  BO: 0.02

FIS:
  TY: 0.75
  TI: 0.18
  AI: 0.03
  TIS: 0.03
  BO: 0.01

L:
  FIS: 0.80
  AIS: 0.18
  U: 0.01
  BO: 0.01

U:
  FIS: 0.80
  AIS: 0.09
  L: 0.09
  BO: 0.02